### ISSUE TITLE
Add a configurable environment variable for script sleep time

### ISSUE THREAD

**Issue by patrickaclark** [patrickaclark/gluetun-qbittorrent-port-manager#3]
## Background
Gluetun logs every call to /v1/openvpn/portforwarded in its container logs, so I initially hard-coded the loop to re-check whether the forwarded port and qbittorents ports match every 10 minutes to cut out some of the chatter.  I realize that some users with busier stacks focused on uptime may want to have more granular control and not care about the frequency of logging.  

I would like to add a configurable variable in the docker-compose.yml so the user can configure how often it checks. 

## Tasks
- [x] Create ENV variable RECHECK_TIME in Dockerfile
- [x] Add variable and create comment in docker-compose.yml
- [x] Call above variable in the sleep section of the loop in start.sh

**Comment by patrickaclark** [comment]
Merged
